build:
  version: 1.0
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3361}/${DB_NAME:bank_ms_db}
    username: root
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

contact:
  environment: "dev"
  email: "dev@server.com"
  phones:
    - 809-549-3625
    - 809-549-5549



