build:
  version: 1.1

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3361}/${DB_NAME:customer_ms_db}
    username: root
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

customer:
  environment: "qa"
  fullname: Julio Luis
  email: jluis@gmail.com

